In [2]:
import numpy as np

arr = [1,2,3,4,5]
np_arr = np.array(arr)
print(type(arr))
print(type(np_arr))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### arange
python의 range 함수와 비슷하게 사용 가능

In [5]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### reshape
**2차원 배열**을 쉽게 만들 수 있음

- Indexing
- Slicing

In [8]:
arr = np.arange(25).reshape(5,5)

print(arr[1][2])

# 1번, 2번 행 / 0번, 1번 열
print(arr[1:3, :2])

7
[[ 5  6]
 [10 11]]


### 얕은 복사와 깊은 복사
- 얕은 복사: 원본 배열을 수정하지 않음
np.copy()

In [9]:
arr2 = arr
arr2[0][0] = 15
print(arr)
print(arr2) # 원본 배열이 바뀌어 버림

[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
arr = np.arange(15).reshape(3,5)
arr2 = arr.copy() # 얕은 복사 -> 원본이 바뀌지 않음
arr2[0][0] = 15
print(arr)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
